#!/bin/bash

# A shortcut for docker-compose 
# Command: 
# docker-compose \
#   -f docker-coompose \
#   -f docker-compose.$ENVNAME.yml \
#   --env-file .env.$ENVNAME \
#   up -d
# May shorten as:
# ./compose $ENVNAME up -d

set -e

usage(){
    echo "Usage:"
    echo "  ./compose <ENVNAME> [options] [--] [COMMAND] [ARGS...]"
    echo
    docker-compose --help | sed -n '/^Options:$/, $p'
}

wrong_params(){
    echo
    usage
    exit 1
}

check_file_exist(){
    if [[ ! -f $1 ]]; then
        echo "ERROR: No such file: $1"
        wrong_params
    fi
}

check_params(){
    if [ $# -lt 1 ]; then
        echo "ERROR: Missing env name"
        wrong_params
    fi
}

check_params "$@"

env_compose_file="docker-compose.${1}.yml"
env_file=".env.${1}"

check_file_exist "$env_compose_file"
check_file_exist "$env_file"

docker-compose \
    -f docker-compose.yml \
    -f "$env_compose_file" \
    --env-file "$env_file" \
    "${@:2}"