version: "3"

services:
  restic:
    build: 
      context: ./restic
    hostname: restic
    environment:
      RESTIC_REPOSITORY:
      RESTIC_PASSWORD:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      RESTIC_TAG: ${RESTIC_TAG}
      RESTIC_FORGET_ARGS: ${RESTIC_FORGET_ARGS}
      RESTIC_JOB_ARGS: ${RESTIC_JOB_ARGS}
      BACKUP_CRON: ${BACKUP_CRON}
      BACKUP_DATABASE_HOST: database
      BACKUP_DATABASE_USER: root
      BACKUP_DATABASE_PASSWORD: ${WIKI_DATABASE_ROOT_PASSWORD}
    volumes:
      - wiki-upload:/data/upload
      - wiki-data:/var/lib/mysql
      - ./restic/hooks:/hooks
    networks: 
      - backend
