FROM mediawiki:1.36

ENV MW_INSTALL_PATH=/var/www/html

# Install system requirement
RUN apt-get update && apt-get install -y \
    sudo \
    libzip-dev \
    zlib1g-dev \
    unzip

# Create user for development
ARG USERNAME=mediawiki
ARG USER_UID=1000
ARG USER_GID=$USER_UID
# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    # Add sudo support
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Install PHP requirement
RUN pecl install redis \
    && docker-php-ext-install zip \
    && docker-php-ext-enable redis zip

# Install Composer
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /tmp/composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
# Config mirror
ARG COMPOSER_MIRROR="https://mirrors.aliyun.com/composer/"
ARG GITHUB_MIRROR="https://github.com.cnpmjs.org"
RUN composer config -g repo.packagist composer $COMPOSER_MIRROR
# Copy Comopser config
COPY ./composer.local.json $MW_INSTALL_PATH/composer.local.json
# Copy install script
COPY ./install_extensions.sh /tmp/install_extensions.sh
# Install extension
RUN /tmp/install_extensions.sh


