#!/bin/sh

prepare_repo(){
    echo "Checking restic repo '${RESTIC_REPOSITORY}'..."
    restic snapshots > /dev/null 2>&1
    repo_statu=$?
    if [ $repo_statu != 0 ]; then
        echo "Restic repo does not exists!"
        init_repo
    else
        echo "Restic repo ready!"
    fi
}

init_repo(){
    echo "Init repo '${RESTIC_REPOSITORY}'..."
    restic init > /dev/null 2>&1
    init_statu=$?
    if [ $init_statu != 0 ]; then
        echo "Failed to init repo!"
        exit $init_statu
    else
        echo "Repo init successful!"
    fi
}

prepare_repo
