#!/bin/sh

backup(){
    echo "Backing up..."
    restic ${RESTIC_OPTIONS} backup "${DATA_DIR}" \
        ${RESTIC_BACKUP_OPTIONS}
}

about_backup_statu(){
    echo "Visit below link to learn more about the status: "
    echo "https://restic.readthedocs.io/en/stable/040_backup.html#exit-status-codes"
}

handle_backup_statu(){
    if [ "$1" = 0 ]; then
        echo "Backup successful!"
    else
        echo "Backup failed with statu $1"
        about_backup_statu
        exit "$1"
    fi
}

echo
backup
handle_backup_statu $?