version: "3"

services: 
  restic:
    build: .
    volumes: 
      - test-upload:/data/upload
      - test-data-dump:/data/database
      - ./jobs:/jobs
    environment: 
      TZ: Asia/Shanghai
      RESTIC_PASSWORD: testpass
      RESTIC_OPTIONS: --verbose
      RESTIC_BACKUP_OPTIONS: --tag test
      RESTIC_FORGET_OPTIONS: --keep-last 5 --prune
      BACKUP_CRON: "*/1 * * * *"
      BACKUP_DATABASE_HOST: mariadb
      BACKUP_DATABASE_NAME: testdb
      BACKUP_DATABASE_USER: test
      BACKUP_DATABASE_PASSWORD: testpass
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb
    environment: 
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: testpass

volumes: 
  test-upload:
  test-data-dump: