<?php
# This file was automatically generated by the MediaWiki 1.35.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# Load setting files
foreach(glob("$IP/mymw/settings/*.php") as $setting){
	require $setting;
}

# Load custom extension/skin
# change extension dir
$wgExtensionDirectory = "$IP/mymw/extensions";
foreach(glob("$IP/mymw/settings/{skins,extensions}/*.php", GLOB_BRACE) as $setting){
	require $setting;
}